apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::089164095823:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::089164095823:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1VD7RUYS52JXX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-03T17:30:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3322"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e635c2ef-46aa-11ea-b5b2-0e8a6b4ac476
