apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::089164095823:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QKOI5POVS5BN
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-31T18:05:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "940"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 42f86246-4454-11ea-b45a-06f6bff2ba44
